version: '3'

services:
  ace-backend:
    # container_name: ace-backend
    build: ./ace_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./ace_backend:/code/ace_backend
    expose:
      - "8000"

  ace-frontend:
    # container_name: ace-frontend
    build: ./ace_frontend
    command: npm start
    volumes:
      - ./ace_frontend:/code/ace_frontend
    ports:
      - "3000:3000"
    depends_on:
      - ace-backend

  proxy:
    build:
      context:  ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    links:
      - ace-backend
