# Generated by Django 2.1.5 on 2019-02-04 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190125_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='sunday',
        ),
    ]
