# Generated by Django 2.1.5 on 2019-02-08 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_section_sunday'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_begin', models.TimeField(null=True)),
                ('time_end', models.TimeField(null=True)),
                ('monday', models.BooleanField()),
                ('tuesday', models.BooleanField()),
                ('wednesday', models.BooleanField()),
                ('thursday', models.BooleanField()),
                ('friday', models.BooleanField()),
                ('saturday', models.BooleanField()),
                ('room', models.CharField(blank=True, max_length=255)),
                ('special_enrollment', models.CharField(blank=True, max_length=255)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Instructor')),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='additional_info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='time_begin',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='time_end',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='lab_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.LabSection'),
        ),
    ]
