# Generated by Django 2.1.5 on 2019-02-08 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20190207_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credit_hours',
            field=models.CharField(max_length=16),
        ),
    ]
