# Generated by Django 2.1.5 on 2019-02-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20190208_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='available_seats',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
