# Generated by Django 2.1.7 on 2019-03-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aceuser',
            name='courses',
            field=models.ManyToManyField(to='courses.Course'),
        ),
    ]
