# Generated by Django 2.1.7 on 2019-03-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_aceuser_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aceuser',
            name='courses',
            field=models.ManyToManyField(to='courses.Section'),
        ),
    ]
