# Generated by Django 2.1.7 on 2019-03-29 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190329_0244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aceuser',
            old_name='courses',
            new_name='sections',
        ),
    ]
